output: main.o cell-h.0 cell.o menu.o menu-h.o tablica.o tablica-h.o tablica_wysw.o tablica_wysw-h.o

main.o: main.cpp
	g++ -c main.cpp

cell-h.o: Cell.h
	g++ -c Cell.h

cell.o: Cell.cpp
	g++ -c Cell.cpp

menu-h.o: Menu.h
	g++ -c Menu.h

menu.o: Menu.cpp
	g++ -c Menu.cpp

tablica-h.o: Table.h
	g++ -c Table.h

tablica.o: Table.cpp
	g++ -c Table.cpp

tablica_wysw-h.o: TableViewer.h
	g++ -c TableViewer.h

tablica_wysw.o: TableViewer.cpp
	g++ -c TableViewer.cpp
